version: '3.9'

services:
  database:
    image: postgres:16
    ports:
      - 55432:5432
    volumes:
      - ./local/postgres:/var/lib/postgres
    environment:
      - POSTGRES_PASSWORD=localpassword
      - POSTGRES_DB=pasali
