name: "Deploy: Auth lambda to AWS"
on:
  push:
    branches:
      - main
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
jobs:
  npm-build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout code
      - uses: actions/setup-node@v4
        name: Setup NodeJS engine
        with:
          node-version: "21.5"
      - run: cd lambda/auth && npm ci
        name: NPM Install
      - run: cd lambda/auth && npm run build
        name: Build code
      - uses: actions/upload-artifact@v4
        name: Upload code
        with:
          name: package
          path: ./lambda/out/auth.zip
  aws-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: npm-build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: package
      - name: Upload package to AWS
        run: aws lambda update-function-code --function-name ${{ vars.LAMBDA_AUTHHOOK }} --zip-file fileb://auth.zip
